spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ouvrage?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: MYSQL
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration